In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
#Prepare the dataset

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
print(df.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0


In [4]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

In [5]:
df.shape

(400, 5)

In [6]:
print(df.isnull().sum())
df = df.dropna()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64


In [7]:
X = df.drop("Purchased", axis=1)  # Independent variables
Y = df['Purchased']                 # Dependent variable

In [8]:
print("Shape of my X= ",X.shape)
print("Shape of my X= ",Y.shape)

Shape of my X=  (400, 4)
Shape of my X=  (400,)


In [9]:
#Train Test Split

In [10]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=20)

In [11]:
X_train.shape
X_test.shape

(100, 4)

In [13]:
X_train.shape

(300, 4)

In [14]:
print("Shape of my X_train= ",X_train.shape)
print("Shape of my X_test= ",X_test.shape)
print("Shape of my Y_train= ",Y_train.shape)
print("Shape of my Y_test= ",Y_test.shape)

Shape of my X_train=  (300, 4)
Shape of my X_test=  (100, 4)
Shape of my Y_train=  (300,)
Shape of my Y_test=  (100,)


In [15]:
SC=StandardScaler()
SC.fit(X_train)
X_train=SC.transform(X_train)
X_test=SC.transform(X_test)

In [16]:
X_train

array([[ 1.49568075, -1.040833  , -0.15785698,  1.4873086 ],
       [-0.39261757,  0.96076892,  1.3515325 , -1.43232715],
       [-0.2733629 ,  0.96076892, -0.25219383, -1.37212847],
       ...,
       [-1.37908611, -1.040833  ,  2.10622724,  1.0057192 ],
       [-0.03903867,  0.96076892,  2.0118904 ,  0.22313642],
       [-1.19810444, -1.040833  ,  2.10622724, -1.04103576]])

In [17]:
lr=LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression()

In [18]:
lr.coef_

array([[ 0.12376668, -0.09711424,  2.06536256,  0.84002288]])

In [20]:
y_pred = lr.predict(X_test)
print("Accuracy:", accuracy_score(Y_test, y_pred))

Accuracy: 0.84


In [21]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))

Confusion Matrix:
 [[56  2]
 [14 28]]


In [22]:
print("Classification Report:\n", classification_report(Y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.97      0.88        58
           1       0.93      0.67      0.78        42

    accuracy                           0.84       100
   macro avg       0.87      0.82      0.83       100
weighted avg       0.86      0.84      0.83       100

